### PR TITLE
voronoi merger inherits mask merger, make destructor virtual

### LINKED ISSUE #30: App crash when trying to stitch on macOS Mojave
Adding a single input is fine, when adding a second input, there's a SIGILL in the MaskMerger destructor.

macOS Mojave, 10.14.6
MBP 13" 2019, Intel Iris Pro 655

```
Thread 6 Crashed:: Controller Thread
0   libvideostitch.dylib          	0x000000010b12c084 VideoStitch::Core::MaskMerger::~MaskMerger() + 4
1   libvideostitch.dylib          	0x000000010b125529 VideoStitch::Core::ImageMerger::~ImageMerger() + 41
2   libvideostitch.dylib          	0x000000010b1223ee VideoStitch::Core::GradientImageMerger::~GradientImageMerger() + 14
3   libvideostitch.dylib          	0x000000010b122a1e VideoStitch::Core::ImageMapping::~ImageMapping() + 78
4   libvideostitch.dylib          	0x000000010b122aae VideoStitch::Core::ImageMapping::~ImageMapping() + 14
5   libvideostitch.dylib          	0x000000010b12eaaf VideoStitch::Core::PanoStitcherImplV1<VideoStitch::Core::StitcherOutput<VideoStitch::Output::VideoWriter> >::~PanoStitcherImplV1() + 79
6   libvideostitch.dylib          	0x000000010b12ebde VideoStitch::Core::PanoStitcherImplV1<VideoStitch::Core::StitcherOutput<VideoStitch::Output::VideoWriter> >::~PanoStitcherImplV1() + 14
7   libvideostitch.dylib          	0x000000010b0e01a2 VideoStitch::Core::PanoPipeline::~PanoPipeline() + 34
8   libvideostitch.dylib          	0x000000010b049a88 non-virtual thunk to VideoStitch::Core::ControllerImpl<VideoStitch::Core::PanoPipeline>::deleteStitcher() + 56
9   libvideostitch-gui.dylib      	0x000000010ad507fc VideoStitcher<VideoStitch::Core::StitcherController<VideoStitch::Core::StitcherOutput<VideoStitch::Output::VideoWriter>, VideoStitch::Core::PanoDeviceDefinition> >::closeProject() + 28
10  libvideostitch-gui.dylib      	0x000000010ad4c283 StitcherController::closeProject() + 35
11  videostitch-studio            	0x000000010abfe752 PostProdStitcherController::resetPano() + 882
12  videostitch-studio            	0x000000010abfec48 PostProdStitcherController::reset() + 24
13  libvideostitch-gui.dylib      	0x000000010ad4c0bd StitcherController::onReset(SignalCompressionCaps*) + 45
14  org.qt-project.QtCore         	0x000000010d694b0a QMetaObject::activate(QObject*, int, int, void**) + 2954
15  libvideostitch-gui.dylib      	0x000000010acfad1c ProjectDefinition::reqReset(SignalCompressionCaps*) + 60
16  videostitch-studio            	0x000000010abaffb5 PostProdProjectDefinition::addInputs(QList<VideoStitch::Ptv::Value*>) + 837
17  videostitch-studio            	0x000000010abfda13 PostProdStitcherController::openInputs(QList<QUrl>, int, int) + 2259
18  videostitch-studio            	0x000000010aba87de QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2>, QtPrivate::List<QList<QUrl>, int, int>, void, void (PostProdStitcherController::*)(QList<QUrl>, int, int)>::call(void (PostProdStitcherController::*)(QList<QUrl>, int, int), PostProdStitcherController*, void**) + 78
```

### PR DESCRIPTION
**Pull request by w-m**
Fixes #30.

MaskMerger factory produces a VoronoiMaskMerger: https://github.com/stitchEm/stitchEm/blob/master/lib/src/core1/maskMerger.cpp#L41

But the MaskMerger (base class) is later deleted: https://github.com/stitchEm/stitchEm/blob/master/lib/src/core1/imageMerger.hpp#L93

Thus the destructor should be virtual.

The destructor was never virtual, code is 4 years old, wonder why this wasn't an issue before. Maybe this is UB and a recent clang version does some optimisation that blows up?

### CODE REVIEW

**Comment by w-m** [comment]
There's a problem with linking to glew now, unrelated to this change.

**Comment by jeremad** [comment]
Indeed

**Comment by w-m** [comment]
Bit weird as glew is still found in CMake configuration. While current CMake supports glew as an imported target (`GLEW::GLEW`) the old `${GLEW_LIBRARIES}` that we are using should still be set: https://cmake.org/cmake/help/latest/module/FindGLEW.html

**Comment by w-m** [comment]
`-- Found GLEW: /usr/local/lib/cmake/glew/glew-config.cmake` uhh why's that pointing to a .cmake file instead of to the library path though

**Comment by jeremad** [comment]
GLEW version is still the same from the latest successful build. CMake has changed though

**Comment by jeremad** [comment]
OK, that's it FindGLEW has changed A LOT between cmake 3.14 and 3.15, as quickfix I can set the CMAKE version I guess, and add a todo...

**Comment by jeremad** [comment]
Actually I can't do that on travis... Do you reproduce locally?

**Comment by w-m** [comment]
Could you try whether replacing GLEW_LIBRARIES in https://github.com/stitchEm/stitchEm/blob/master/lib/libvideostitch_OpenCL.cmake#L120 with GLEW::GLEW fixes Travis?

I'm using MacPorts locally where this wasn't an issue (neither for filmcafeSteve as it seems), but I'm not sure of the CMake version used. Can check later today.

**Comment by jeremad** [comment]
Fixed in here:
https://github.com/stitchEm/stitchEm/pull/34

File: lib/src/core1/voronoiMaskMerger.hpp [hunk 1]
```diff
@@ -14,7 +14,7 @@ namespace Core {
 class VoronoiMaskMerger : public MaskMerger {
  public:
   VoronoiMaskMerger() : feather(0) {}
-  ~VoronoiMaskMerger() {}
+  virtual ~VoronoiMaskMerger() override {}
```
Comment (StephaneValente) [inline lib/src/core1/voronoiMaskMerger.hpp]: There is a bit a discussion on stackoverflow, whether the override keyword is needed for virutal destructors (because they are not overriding anything, they are chained). 
The virtual keyword may also be redundant, since it derived from a class with a virtual destructor, the destructor in the derived class will implicitely be virtual.

Comment (w-m) [reply lib/src/core1/voronoiMaskMerger.hpp]: I've had a quick look too, yikes, another controversial topic in C++. Indeed, it's redundant when the base class has a virtual destructor. But it seems to be a good safeguard about accidental removal of the virtual keyword on the base class destructor. Then it wouldn't compile any more (https://stackoverflow.com/a/17923488/463796). So I think we can leave it in.
